name: vincentlg
favicon: null
layout_spectrum: 0.38871806068345904
typography_spectrum: 0.7802426102571189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6116754033137113
  lightness: 0.5132993233855814
  saturation: 0.7942845735233277
  rhythmicContrast: 0.027741505298763514
purpose: []
